<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter

In [2]:
%pip install psycopg2

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2 in /usr/lib64/python3.13/site-packages (2.9.9)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import psycopg2
import requests
from bs4 import BeautifulSoup

In [4]:
# вставьте сюда параметры подключения из юнита 1. Работа с базой данных из Python
DBNAME = 'project_sql'
USER = 'skillfactory'
PASSWORD = 'cCkxxLVrDE8EbvjueeMedPKt'
HOST = '84.201.134.129'
PORT = 5432

In [5]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies).

In [6]:
# текст запроса
query_3_1 = f'''
select
   count(*) as cnt_vacancy
from
   vacancies
'''

In [7]:
# результат запроса
df = pd.read_sql_query(query_3_1, connection)
#connection.close()
df

/tmp/ipykernel_8563/301560860.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_1, connection)

   cnt_vacancy
0        49197

2. Напишите запрос, который посчитает количество работодателей (таблица employers).

In [8]:
# текст запроса
query_3_2 = f'''
select
    count(*) as cnt_employers
from
    employers
'''

In [9]:
# результат запроса
df = pd.read_sql_query(query_3_2, connection)
#connection.close()
df

/tmp/ipykernel_8563/303172622.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_2, connection)

   cnt_employers
0          23501

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [10]:
# текст запроса
query_3_3 = f'''
select
    count(*) as cnt_regions
from
    areas
'''

In [11]:
# результат запроса
df = pd.read_sql_query(query_3_3, connection)
#connection.close()
df

/tmp/ipykernel_8563/4269440589.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_3, connection)

   cnt_regions
0         1362

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [12]:

# текст запроса
query_3_4 = f'''
select
    count(*) as cnt_industries
from
    industries
'''

In [13]:
# результат запроса
df = pd.read_sql_query(query_3_4, connection)
df

/tmp/ipykernel_8563/2101691108.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_4, connection)

   cnt_industries
0             294

***

In [14]:
# выводы по предварительному анализу данных
# Колличество регионов не соответствует действительности

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [15]:
# текст запроса
query_4_1 = f'''select
                    a.name area,
                    count(a.id) cnt
                from
                    vacancies v
                join
                    areas a on v.area_id = a.id
                group by 1
                order by 2 DESC
'''

In [16]:
# результат запроса
df = pd.read_sql_query(query_4_1, connection)
df

/tmp/ipykernel_8563/2457173557.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_1, connection)

                area   cnt
0             Москва  5333
1    Санкт-Петербург  2851
2              Минск  2112
3        Новосибирск  2006
4             Алматы  1892
..               ...   ...
764       Тарко-Сале     1
765    Новоаннинский     1
766            Бирск     1
767           Сасово     1
768             Анна     1

[769 rows x 2 columns]

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [17]:
# текст запроса
query_4_2 = f'''select
                    count(id)
                from
                    vacancies
                where salary_from is not null or salary_to is not null
'''

In [18]:
# результат запроса
df = pd.read_sql_query(query_4_2, connection)
df

/tmp/ipykernel_8563/970655580.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_2, connection)

   count
0  24073

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [19]:
# текст запроса
query_4_3 = f'''select
                    avg(salary_from) mean_from,
                    avg(salary_to) mean_to
                from
                    vacancies
'''

In [20]:
# результат запроса
df = pd.read_sql_query(query_4_3, connection)
df

/tmp/ipykernel_8563/2500607024.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_3, connection)

      mean_from        mean_to
0  71064.657901  110536.741923

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.

In [21]:
# текст запроса
query_4_4 = f'''select
                    format('%s - %s',schedule,employment),
                    count(id)
                from
                    vacancies
                group by 1
                order by 2 desc
'''

In [22]:
df = pd.read_sql_query(query_4_4, connection)
df

/tmp/ipykernel_8563/2981602351.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_4, connection)

                                    format  count
0           Полный день - Полная занятость  35367
1      Удаленная работа - Полная занятость   7802
2         Гибкий график - Полная занятость   1593
3   Удаленная работа - Частичная занятость   1312
4        Сменный график - Полная занятость    940
5                 Полный день - Стажировка    569
6        Вахтовый метод - Полная занятость    367
7        Полный день - Частичная занятость    347
8      Гибкий график - Частичная занятость    312
9           Полный день - Проектная работа    141
10     Удаленная работа - Проектная работа    133
11              Гибкий график - Стажировка    116
12    Сменный график - Частичная занятость    101
13           Удаленная работа - Стажировка     64
14        Гибкий график - Проектная работа     18
15             Сменный график - Стажировка     12
16       Вахтовый метод - Проектная работа      2
17       Сменный график - Проектная работа      1

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта.

In [23]:
# текст запроса
query_4_5 = f'''
select
    format($$ Требуемый опыт работы ( %s ) $$,experience) "Опыт работы",
    count(experience)
from
    vacancies
group by experience
order by 2
'''

In [24]:
# результат запроса
df = pd.read_sql_query(query_4_5, connection)
df

/tmp/ipykernel_8563/2316260449.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_5, connection)

                                      Опыт работы  count
0          Требуемый опыт работы ( Более 6 лет )    1337
1            Требуемый опыт работы ( Нет опыта )    7197
2        Требуемый опыт работы ( От 3 до 6 лет )   14511
3   Требуемый опыт работы ( От 1 года до 3 лет )   26152

***

In [25]:
# выводы по детальному анализу вакансий
# наиболее востребованые вакансии с опытом работы от 1 года до 3х, а наименее востребованные более 6 лет

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [26]:
# текст запроса
query_5_1 = f'''
select
    em.name company_name,
    count(v.id)
from
    vacancies as v
join
    employers as em on em.id = v.employer_id
group by 1
order by 2 desc
limit 5
'''

In [27]:
# результат запроса
df = pd.read_sql_query(query_5_1, connection)
df

/tmp/ipykernel_8563/3834399874.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_1, connection)

    company_name  count
0         Яндекс   1933
1     Ростелеком    491
2       Тинькофф    444
3           СБЕР    428
4  Газпром нефть    331

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.

In [28]:
# текст запроса
query_5_2 = f'''
-- Для каждого региона: количество работодателей и вакансий
select
    a.name as region_name,
    count(distinct e.id) as cnt_employers,
    count(v.id) as cnt_vacancies
from
    areas a
left join
    employers e on e.area = a.id
left join
    vacancies v on v.area_id = a.id
where v.id is null
group by
    a.id, a.name
order by
    cnt_vacancies desc, cnt_employers desc;

'''

In [29]:
# результат запроса
df = pd.read_sql_query(query_5_2, connection)
df

/tmp/ipykernel_8563/2250345976.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_2, connection)

            region_name  cnt_employers  cnt_vacancies
0                Россия            410              0
1             Казахстан            207              0
2    Московская область             75              0
3    Краснодарский край             19              0
4    Ростовская область             18              0
..                  ...            ...            ...
588             Скидель              0              0
589          Белоозерск              0              0
590           Орловский              0              0
591          Павловская              0              0
592             Таксимо              0              0

[593 rows x 3 columns]

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.

In [30]:
# текст запроса
query_5_3 = f'''
select
    e.name as company_name,
    count(distinct a.name) as cnt_region
from
    employers as e
join
    vacancies as v on v.employer_id = e.id
join
    areas as a on a.id = v.area_id
where v.id is not null
group by 1
order by 2 desc
'''

In [31]:
df = pd.read_sql_query(query_5_3, connection)
df

/tmp/ipykernel_8563/2398953733.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_3, connection)

                 company_name  cnt_region
0                      Яндекс         181
1                  Ростелеком         152
2                  Спецремонт         116
3      Поляков Денис Иванович          88
4                   ООО ЕФИН           71
...                       ...         ...
14761                  UniSol           1
14762            UNISTORY LLC           1
14763                   UNIT6           1
14764     United Distribution           1
14765              UNITEL LLC           1

[14766 rows x 2 columns]

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности.

In [32]:
query_5_4 = f'''
select
    count(*) as cnt
from
    employers as em
left join
    employers_industries as em_i on em_i.employer_id = em.id
left join
    industries as i on i.id = em_i.industry_id
where i.id is null

'''

In [33]:
df = pd.read_sql_query(query_5_4, connection)
df

/tmp/ipykernel_8563/3114411492.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_4, connection)

    cnt
0  8419

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности.

In [34]:
query_5_5 = f'''
select
    em.name
from
    employers as em
left join
    employers_industries as em_i on em_i.employer_id = em.id
left join
    industries as i on i.id = em_i.industry_id
group by em.name
-- выбираем компании с четырьмя сферами деятельности
having count(i.name)=4
order by 1
-- оставляем три компнании
limit 3
'''

In [35]:
df = pd.read_sql_query(query_5_5, connection)
df

/tmp/ipykernel_8563/1650419958.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_5, connection)

           name
0  101 Интернет
1      21vek.by
2          2ГИС

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.

In [36]:
query_5_6 = f'''
SELECT
    COUNT(DISTINCT ei.employer_id) AS employers_count
FROM
    employers_industries ei
JOIN
    industries i ON ei.industry_id = i.id
WHERE
    i.name = 'Разработка программного обеспечения'
'''

In [37]:
df = pd.read_sql_query(query_5_6, connection)
df

/tmp/ipykernel_8563/1169039133.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_6, connection)

   employers_count
0             3553

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8). 

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API.

In [38]:
# код для получения списка городов-милионников
import requests, re
from bs4 import BeautifulSoup

URL = f"https://api.wikimedia.org/core/v1/wikipedia/ru/page/Города-миллионеры_России/html"
HEADERS = {
    "User-Agent": "MillionCitiesFetcher/1.0 (+contact: your_email@example.com)"
}
# переменная для сохранения результата запроса
r = requests.get(URL, headers=HEADERS, timeout=20)
r.raise_for_status()
# структурируем информацию
soup = BeautifulSoup(r.text, "html.parser")
# основной список — первая таблица
table = soup.find("table")
# нам потребуется переменная для списка
rows = []
# разбираем текст и формируем список
for tr in table.find_all("tr")[1:]:
    tds = [td.get_text(strip=True) for td in tr.find_all("td")]
    if len(tds) < 3:
        continue
    if not tds[0].isdigit():
        continue
    city = tds[1]
    pop_2025 = int(re.sub(r"[^\d]", "", tds[2])) if tds[2] else 0
    if pop_2025 >= 1000:
        rows.append(city)

print(", ".join(rows))

Москва, Санкт-Петербург, Новосибирск, Екатеринбург, Казань, Красноярск, Нижний Новгород, Челябинск, Уфа, Краснодар, Самара, Ростов-на-Дону, Омск, Воронеж, Пермь, Волгоград

In [39]:
# текст запроса
query_5_7 = f'''
select
    ar.name,
    count(v.id) cnt
from
    vacancies as v
join
    employers as em on v.employer_id = em.id
join
    areas as ar on ar.id = v.area_id
where em.name like 'Яндекс'
group by 1
order by 2
'''

In [40]:
# результат запроса отсортировать
df = pd.read_sql_query(query_5_7, connection)
# сортировка запроса
df = df[df.name.isin(rows)]

# строка для добавления в таблицу
now_df = pd.DataFrame([{'name': 'Total', 'cnt': df.cnt.sum()}])
df = pd.concat([df, now_df], ignore_index=True)
df

/tmp/ipykernel_8563/2072237716.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_7, connection)

               name  cnt
0              Омск   21
1         Челябинск   22
2        Красноярск   23
3         Волгоград   24
4             Пермь   25
5            Казань   25
6    Ростов-на-Дону   25
7               Уфа   26
8            Самара   26
9         Краснодар   30
10          Воронеж   32
11      Новосибирск   35
12  Нижний Новгород   36
13     Екатеринбург   39
14  Санкт-Петербург   42
15           Москва   54
16            Total  485

***

In [41]:
# выводы по анализу работодателей
# работодатель яндекс показал себя как наиболее геораспределенным

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.*

In [42]:
query_6_1 = f'''
select
    count(v.name) cnt
from
    vacancies as v
where lower(v.name) like '%data%' or lower(v.name) like '%данн%'
'''

In [43]:
# результат запроса
df = pd.read_sql_query(query_6_1, connection)
df

/tmp/ipykernel_8563/366702258.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_1, connection)

    cnt
0  1771

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста? 
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.

In [44]:
# текст запроса
query_6_2 = f'''
select
    count(*) cnt
from
    vacancies as v
where (lower(v.name) like '%data scientist%' or
    lower(v.name) like '%data science%' or
    lower(v.name) like '%исследователь данных%' or
    (v.name like '%ML%' and v.name not like '%HTML%') or
    lower(v.name) like '%machine learning%' or
    lower(v.name) like '%машинн%обучен%') and
    (lower(v.name) like '%junior%' or
    lower(v.experience) like '%нет опыта%' or
    lower(v.employment) like 'стажировка')
'''

In [45]:
# результат запроса
df = pd.read_sql_query(query_6_2, connection)
df

/tmp/ipykernel_8563/2267038862.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_2, connection)

   cnt
0   51

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [46]:
# текст запроса
query_6_3 = f'''
select
    count(*) cnt
from
    vacancies as v
where
    (
        lower(v.name) like '%data scientist%' or
        lower(v.name) like '%data science%' or
        lower(v.name) like '%исследователь данных%' or
        (
            lower(v.name) like '%ml%' and
            lower(v.name) not like '%html%'
        ) or
        lower(v.name) like '%machine learning%' or
        lower(v.name) like '%машинн%обучен%'
    ) and
    (
        lower(v.key_skills) like '%postgres%' or
        lower(v.key_skills) like '%sql%'
    )
'''

In [47]:
# результат запроса
df = pd.read_sql_query(query_6_3, connection)
df

/tmp/ipykernel_8563/3794299702.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_3, connection)

   cnt
0  229

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [48]:
query_6_4 = f'''
select
    count(*) cnt
from
    vacancies as v
where
    (
    lower(v.name) like '%data scientist%' or
    lower(v.name) like '%data science%' or
    lower(v.name) like '%исследователь данных%' or
    (
        lower(v.name) like '%ml%' and
        lower(v.name) not like '%html%'
    ) or
    lower(v.name) like '%machine learning%' or
    lower(v.name) like '%машинн%обучен%'
    )
    and
    lower(v.key_skills) like '%python%'
'''

In [49]:
df = pd.read_sql_query(query_6_4, connection)
df

/tmp/ipykernel_8563/972386973.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_4, connection)

   cnt
0  357

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [50]:
query_6_5 = f'''
select
    avg(skill_count) as avg_skills
from
    (
        select
            v.id,
            -- Считаем количество табуляций и добавляем 1
            (length(v.key_skills) - length(replace(v.key_skills, chr(9), '')) + 1) as skill_count
        from
            vacancies as v
        where
            (
                lower(v.name) like '%data scientist%' or
                lower(v.name) like '%data science%' or
                lower(v.name) like '%исследователь данных%' or
                (
                    v.name like '%ML%' and
                    v.name not like '%HTML%'
                ) or
                lower(v.name) like '%machine learning%' or
                lower(v.name) like '%машинн%обучен%'
            ) and
            v.key_skills is not NULL and  -- Исключаем NULL
            v.key_skills not like ''            -- Исключаем пустые строки
    ) as skills_per_vacancy
'''

In [51]:
df = pd.read_sql_query(query_6_5, connection)
df

/tmp/ipykernel_8563/390248827.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_5, connection)

   avg_skills
0    6.406032

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*). 

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа.

In [52]:
query_6_6 = f'''
select
    v.experience,
    round(avg(
            case
                when v.salary_from is not null and v.salary_to is not null then
                    (v.salary_from + v.salary_to) / 2
                when v.salary_from is not null then
                    v.salary_from
                when v.salary_to is not null then
                    v.salary_to
            end
    )) as avg_salary
    
from
    vacancies as v
where
    (
        lower(v.name) like '%data scientist%' or
        lower(v.name) like '%data science%' or
        lower(v.name) like '%исследователь данных%' or
        (
                    v.name like '%ML%' and
                    v.name not like '%HTML%'
        ) or
        lower(v.name) like '%machine learning%' or
        lower(v.name) like '%машинн%обучен%'
    )
group by v.experience
order by v.experience
'''

In [53]:
df = pd.read_sql_query(query_6_6, connection)
df

/tmp/ipykernel_8563/3561045109.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_6, connection)

           experience  avg_salary
0         Более 6 лет         NaN
1           Нет опыта     74643.0
2  От 1 года до 3 лет    139675.0
3       От 3 до 6 лет    243115.0

***

In [54]:
# выводы по предметному анализу
# 1. Для опыта работы более 6 лет, работадатели не указывают зарплату
# 2. Без опыта работы DS может получать в среднем от 74 тысяч рублей

# Общий вывод по проекту

In [ ]:
# подведем итог исследования, обобщите выводы:

# * большинство предложений рассчитано на специалистов с опытом от 1 до 6 лет, а зарплаты существенно растут с опытом и заметной долей вакансий с полным рабочим днём и очным форматом работы
# * рынок в основном ориентирован на полную занятость с фиксированным графиком;
# * удалённая работа представлена заметно, но всё ещё существенно уступает классическому офисному формату;

# здесь можно (это будет плюсом) провести дополнительные исследования данных, сделать прогнозы, продумать варианты продолжения исследования

/tmp/ipykernel_8563/2475600858.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_7, connection)

'  * ключевым городам (Москва, СПб, Новосибирск и т.д.);\n * уровням опыта;\n * форматам занятости (офис/удалёнка/гибрид);\n * отраслям. '

In [ ]:
# Наиболее ценные навыки на рынке труда (зарплата > 200000)
query_6_7 = f'''
SELECT
    -- убираем пробелы из навыков
    TRIM(regexp_split_to_table(key_skills, E'\\t')) as skill,
    COUNT(*) as frequency,
    ROUND(AVG((salary_from + salary_to) / 2)::numeric, 0) as avg_salary
FROM vacancies
WHERE salary_from IS NOT NULL
  AND salary_to IS NOT NULL
  AND (salary_from + salary_to) / 2 > 200000
  AND key_skills IS NOT NULL
GROUP BY skill
ORDER BY frequency DESC
LIMIT 30;
'''

In [ ]:
df = pd.read_sql_query(query_6_7, connection)
df

                   skill  frequency  avg_salary
0                    Git        199    262756.0
1                    SQL        147    264461.0
2             JavaScript        145    278215.0
3             PostgreSQL        131    280832.0
4                 Docker        107    266832.0
5                 Python        101    296830.0
6        Английский язык         95    278867.0
7                   Java         94    289806.0
8                  Linux         91    254600.0
9                  MySQL         86    240356.0
10                   ООП         85    231166.0
11               Node.js         68    290956.0
12                   PHP         66    263484.0
13                 Redis         53    248292.0
14            TypeScript         51    257423.0
15            Kubernetes         50    276911.0
16                 React         48    279357.0
17               Android         43    268653.0
18                   AWS         39    338388.0
19                   iOS         39    265574.0
20   1С программирование         39    248046.0
21               Symfony         38    230991.0
22                Kotlin         37    302223.0
23                   CSS         36    260549.0
24                 HTML5         34    258265.0
25               MongoDB         34    273747.0
26      Spring Framework         32    272069.0
27  Управление проектами         32    283161.0
28                  HTML         31    264126.0
29                   C++         30    318582.0

# Можно построить распределения зарплат по:
 * ключевым городам (Москва, СПб, Новосибирск и т.д.);
 * уровням опыта;
 * форматам занятости (офис/удалёнка/гибрид);
 * отраслям.